### ISSUE TITLE
Feature request: queryDSGRN 

### ISSUE THREAD

**Issue by breecummins** [shaunharker/DSGRN#21]
I would like the dsgrnDatabase object to be able to return a network spec in string format.

**Comment by shaunharker** [comment]
It turns out `database.network` gives access to the underlying C++ class which has python wrappers for its member functions, so what we want here can be accomplished with

```
print(database.network.specification())
```

I've updated the python notebook doc to demonstrate this. In general there will be more hidden features like this I need to find a good way of documenting.
