### ISSUE TITLE
queryDSGRN incompatible with parameter graph

### ISSUE THREAD

**Issue by breecummins** [shaunharker/DSGRN#25]
```
File "/share/data/bcummins/DSGRN/software/PythonQuery/queryDSGRN.py", line 88, in __init__
    self.D = self.parametergraph.dimension()
AttributeError: 'ParameterGraph' object has no attribute 'dimension'
```

Sorry if I caught you in the middle of edits. I also have outstanding edits in queryDSGRN in a pull request.

**Comment by shaunharker** [comment]
Any change on this? I couldn't replicate it. Using the `test.db` in the tutorial:

``` python
from queryDSGRN import *
database = dsgrnDatabase("test.db")
database.parametergraph.dimension()
```

resulted in "3L" (which is correct). Install problem?

**Comment by breecummins** [comment]
Hi Shaun,

I still have the issue. I'm on conley3. I pulled the master branch from
your repository and reinstalled DSGRN and then the python install script. I
am still getting the error.

[bcummins@conley3 NetworkPerturbations]$  ipython

Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32)

Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.

?         -> Introduction and overview of IPython's features.

%quickref -> Quick reference.

help      -> Python's own help system.

object?   -> Details about 'object', use 'object??' for extra details.

In [_1_]: from queryDSGRN import *

In [_2_]:
database=dsgrnDatabase("/share/data/CHomP/Projects/DSGRN/DB/data/3D_Cycle.db")

_---------------------------------------------------------------------------_

_AttributeError_                            Traceback (most recent call
last)

_<ipython-input-2-d3500ce205a9>_ in <module>_()_

_----> 1_ database_=_dsgrnDatabase_(_
_"/share/data/CHomP/Projects/DSGRN/DB/data/3D_Cycle.db"__)_

_/share/data/bcummins/DSGRN/software/PythonQuery/queryDSGRN.pyc_ in
**init**_(self,
database_name)_

```
 86     self*.*parametergraph *=* DSGRN*.*ParameterGraph*(*self*.*
```

network_)_

```
 87     *# D is the number of network nodes*
```

_---> 88_     self_._D _=_ self_._parametergraph_._dimension_()_

```
 89     self*.*names *=* *[* self*.*network*.*name*(*i*)* *for* i *in*
```

range_(__0__,_ self_._D_)]_

```
 90     *# DSGRN uses an indexing scheme to refer to parameters. It is
```

based on a mixed-radix number scheme*

_AttributeError_: 'ParameterGraph' object has no attribute 'dimension'

**Comment by shaunharker** [comment]
The problem ended up being due to an old installed version conflicting. The installer asks for either
1. to use the setuptools "python setup.py install" approach, or
2. append to PYTHONPATH. 

If an earlier install uses approach (1) and a later install uses approach (2), then Python will find the earlier install instead of the new install.

This seems to be the wrong behavior on Python's part. The issue is discussed in http://stackoverflow.com/questions/5984523/eggs-in-path-before-pythonpath-environment-variable

The solution is to either 
1. Manually delete the "egg" in the python modules
2. Use approach (1) instead of approach (2).
