### ISSUE TITLE
MorseGraphDrawGraph(DomainGraph(parameter_graph.parameter(i))) and database.DrawMorseGraph(i) producing different graphs

### ISSUE THREAD

**Issue by yingxinac** [shaunharker/DSGRN#40]
I created a database and its parameter graph:

**_from DSGRN import *
database = Database("EMT.db")
parameter_graph = database.parametergraph_**

and then randomly picked an index 1000 and drew the corresponding Morse graph in two different ways:

**_database.DrawMorseGraph(1000)_** 

and

**_MG1000 = MorseGraph(DomainGraph(parameter_graph.parameter(1000)))
DrawGraph(MG1000)_**

But they are giving me two different Morse graphs.  I am wondering whether the indexing schemes in database and in the corresponding parameter graph are the same.

**Comment by shaunharker** [comment]
I can see why this causes confusion. The indexing schemes are different as in fact it turns out two different things are being indexed: Morse Graphs, by "MorseGraphIndex", and combinatorial parameters, by "ParameterIndex". Why they are not the same is because more than one parameter can have the same Morse graph, so the database structure labels distinct Morse Graphs with "MorseGraphIndex" indices. The database has a table which gives the mapping from each ParameterIndex to the not-necessarily-unique "MorseGraphIndex".  (This design prevents duplicate storage of the same Morse Graph.) This table is accessible via `database.__call__` (e.g. `database(1000)`, which accepts ParameterIndex 1000 and returns the associated MorseGraphIndex). Another table in the database gives the mapping from MorseGraphIndex to actual Morse Graphs. This table is the one accessed via the `database.DrawMorseGraph` call, i.e. for

    database.DrawMorseGraph(1000)

what is being retrieved is  a (picture of a) Morse Graph which has been assigned the "MorseGraphIndex" 1000, while in 

    MG1000 = MorseGraph(DomainGraph(parameter_graph.parameter(1000)))

what is being retrieved is the Morse Graph corresponding to "ParameterIndex" 1000.

What should work is

    database.DrawMorseGraph(database(1000))

which will call the `__call__` routine which retrieves from the database the MorseGraphIndex corresponding to a ParameterIndex, and then pass that to DrawMorseGraph.

**Comment by yingxinac** [comment]
Thank you very much!
